<a href="https://colab.research.google.com/github/jasen8651/python001/blob/master/Untitled27.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
## 구글 드라이브 연결
from google.colab import drive
drive.mount('/content/drive')

#  경로 변경
%cd /content/drive/MyDrive/python_demo

Mounted at /content/drive
/content/drive/MyDrive/python_demo

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/python_demo/pdsample/숙소정보크롤링.csv', sep=',', encoding='cp949')
df

,Unnamed: 0,숙소id,숙박이름,객실타입,타입,체크인,체크아웃,번호,주소,대분류,중분류,소분류,X,Y,메인 이미지,공지사항,숙소소개
0,0,24208,제주 T무인텔,1,Motel,18:00,12:00,5.035050e+10,제주특별자치도 제주시 조천읍 남조로 2393,제주시,조천읍,한림읍 협재로 68-5,126.246960,33.392206,https://yaimg.yanolja.com/v5/2018/09/10/16/640...,NaN,NaN
1,1,24993,제주 한림 이쁜새이쁘게노래하고,1,Motel,15:00,11:00,5.035050e+10,제주특별자치도 제주시 한림읍 협재로 68-5,제주시,한림읍,삼무로1길 10-7,126.488756,33.490385,https://yaimg.yanolja.com/resize/place/v4/2017...,"15평 원룸 객실 (크리스탈, 토파즈, 루비)는 객실 지정이 불가",NaN
2,2,26406,제주 JM,1,Motel,14:00,12:00,NaN,제주특별자치도 제주시 삼무로1길 10-7,제주시,삼무로,애월읍 애월해안로 943,126.395764,33.483672,https://yaimg.yanolja.com/v5/2021/12/24/10/640...,NaN,NaN
3,3,26412,제주 Fantastic Oceanview 시드니호텔,1,Motel,15:00,11:00,5.035050e+10,제주특별자치도 제주시 애월읍 애월해안로 943,제주시,애월읍,삼무로1길 3,126.489540,33.491116,https://yaimg.yanolja.com/v5/2019/11/27/11/640...,NaN,1. 최대인원 이상의 인원추가는 불가합니다.\n2. 기준인원 초과 시 추가요금이 발...
4,4,26442,제주 하루,1,Motel,15:00,12:00,5.035053e+10,제주특별자치도 제주시 삼무로1길 3,제주시,삼무로,사장1길 26 (연동),126.492900,33.485324,https://yaimg.yanolja.com/v5/2022/03/15/13/640...,NaN,이용 6일전 오후3시 이전 취소 요청시 100%\n이용 5일전 오후3시 이전 취소 ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1536,1536,1000123163,제주 달콤한아침펜션,3,Pension,17:00,10:00,5.035059e+10,제주특별자치도 제주시 구좌읍 행원로 35-9,제주시,구좌읍,영평5길 68,126.578177,33.484781,https://yaimg.yanolja.com/v5/2023/01/02/10/640...,NaN,옥상에서 바다 감상 가능 / 빔프로젝터 / 조식 / 월정리 해수욕장 도보 5분 / ...
1537,1537,1000123573,제주 다님독채풀빌라,3,Pension,16:00,11:00,5.035059e+10,제주특별자치도 제주시 영평5길 68,제주시,영평5길,애월읍 소길남길 22,126.378132,33.432721,https://yaimg.yanolja.com/v5/2023/01/10/10/640...,NaN,NaN
1538,1538,1000123574,제주 알프스인소길스테이펜션,3,Pension,16:00,11:00,5.035059e+10,제주특별자치도 제주시 애월읍 소길남길 22,서귀포시,애월읍,안덕면 소기왓로 79-1,126.368743,33.241566,https://yaimg.yanolja.com/v5/2023/02/20/11/640...,NaN,NaN
1539,1539,1000123575,서귀포 제주애풀빌라,3,Pension,16:00,11:00,5.035059e+10,제주특별자치도 서귀포시 안덕면 소기왓로 79-1,제주시,안덕면,애월읍 신엄1길 12,126.358504,33.468967,https://yaimg.yanolja.com/v5/2023/01/10/10/640...,NaN,NaN
1540,1540,1000123595,제주 애월애휴양펜션,3,Pension,15:00,11:00,5.035059e+10,제주특별자치도 제주시 애월읍 신엄1길 12,NaN,애월읍,NaN,NaN,NaN,https://yaimg.yanolja.com/v5/2023/02/07/01/640...,NaN,개별 바베큐 /단독 독채 / 오션뷰 / 객실 내 무료 Wi-Fi / 반려동물 동반가...

In [ ]:
year_df=pd.read_csv('/content/drive/MyDrive/python_demo/pdsample/리뷰태그.csv', sep=',', encoding='cp949')
year_df

             숙소id  태그2
0           24208  깨끗함
1           24208  NaN
2           24208  NaN
3           24208  친절함
4           24208  NaN
...           ...  ...
27598  1000122715  깨끗함
27599  1000122715  NaN
27600  1000122715  깨끗함
27601  1000122715   외관
27602  1000123163  깨끗함

[27603 rows x 2 columns]

In [ ]:
df['숙소id'] = year_df['숙소id'].apply(str)

In [ ]:
data=pd.merge(df, year_df, on=['숙소id'], how='inner')
data

,Unnamed: 0,숙소id,숙박이름,객실타입,타입,체크인,체크아웃,번호,주소,대분류,중분류,소분류,X,Y,메인 이미지,공지사항,숙소소개,태그2
0,0,24208,제주 T무인텔,1,Motel,18:00,12:00,5.035050e+10,제주특별자치도 제주시 조천읍 남조로 2393,제주시,조천읍,한림읍 협재로 68-5,126.246960,33.392206,https://yaimg.yanolja.com/v5/2018/09/10/16/640...,NaN,NaN,깨끗함
1,0,24208,제주 T무인텔,1,Motel,18:00,12:00,5.035050e+10,제주특별자치도 제주시 조천읍 남조로 2393,제주시,조천읍,한림읍 협재로 68-5,126.246960,33.392206,https://yaimg.yanolja.com/v5/2018/09/10/16/640...,NaN,NaN,NaN
2,0,24208,제주 T무인텔,1,Motel,18:00,12:00,5.035050e+10,제주특별자치도 제주시 조천읍 남조로 2393,제주시,조천읍,한림읍 협재로 68-5,126.246960,33.392206,https://yaimg.yanolja.com/v5/2018/09/10/16/640...,NaN,NaN,NaN
3,0,24208,제주 T무인텔,1,Motel,18:00,12:00,5.035050e+10,제주특별자치도 제주시 조천읍 남조로 2393,제주시,조천읍,한림읍 협재로 68-5,126.246960,33.392206,https://yaimg.yanolja.com/v5/2018/09/10/16/640...,NaN,NaN,친절함
4,0,24208,제주 T무인텔,1,Motel,18:00,12:00,5.035050e+10,제주특별자치도 제주시 조천읍 남조로 2393,제주시,조천읍,한림읍 협재로 68-5,126.246960,33.392206,https://yaimg.yanolja.com/v5/2018/09/10/16/640...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27437,1533,1000122715,제주 델마펜션,3,Pension,16:00,11:00,5.035059e+10,제주특별자치도 제주시 연대마을길 16-8,제주시,연대마을,애월읍 고성서3길 19,126.411661,33.465629,https://yaimg.yanolja.com/v5/2022/11/09/15/640...,NaN,NaN,깨끗함
27438,1533,1000122715,제주 델마펜션,3,Pension,16:00,11:00,5.035059e+10,제주특별자치도 제주시 연대마을길 16-8,제주시,연대마을,애월읍 고성서3길 19,126.411661,33.465629,https://yaimg.yanolja.com/v5/2022/11/09/15/640...,NaN,NaN,NaN
27439,1533,1000122715,제주 델마펜션,3,Pension,16:00,11:00,5.035059e+10,제주특별자치도 제주시 연대마을길 16-8,제주시,연대마을,애월읍 고성서3길 19,126.411661,33.465629,https://yaimg.yanolja.com/v5/2022/11/09/15/640...,NaN,NaN,깨끗함
27440,1533,1000122715,제주 델마펜션,3,Pension,16:00,11:00,5.035059e+10,제주특별자치도 제주시 연대마을길 16-8,제주시,연대마을,애월읍 고성서3길 19,126.411661,33.465629,https://yaimg.yanolja.com/v5/2022/11/09/15/640...,NaN,NaN,외관
27441,1536,1000123163,제주 달콤한아침펜션,3,Pension,17:00,10:00,5.035059e+10,제주특별자치도 제주시 구좌읍 행원로 35-9,제주시,구좌읍,영평5길 68,126.578177,33.484781,https://yaimg.yanolja.com/v5/2023/01/02/10/640...,NaN,옥상에서 바다 감상 가능 / 빔프로젝터 / 조식 / 월정리 해수욕장 도보 5분 / ...,깨끗함

In [ ]:
data2 = pd.DataFrame(data)
data2.to_csv('숙소태그추가.csv',index=False,mode="a")

In [ ]:
data2

,Unnamed: 0,숙소id,숙박이름,객실타입,타입,체크인,체크아웃,번호,주소,대분류,중분류,소분류,X,Y,메인 이미지,공지사항,숙소소개,태그2
0,0,24208,제주 T무인텔,1,Motel,18:00,12:00,5.035050e+10,제주특별자치도 제주시 조천읍 남조로 2393,제주시,조천읍,한림읍 협재로 68-5,126.246960,33.392206,https://yaimg.yanolja.com/v5/2018/09/10/16/640...,NaN,NaN,깨끗함
1,0,24208,제주 T무인텔,1,Motel,18:00,12:00,5.035050e+10,제주특별자치도 제주시 조천읍 남조로 2393,제주시,조천읍,한림읍 협재로 68-5,126.246960,33.392206,https://yaimg.yanolja.com/v5/2018/09/10/16/640...,NaN,NaN,NaN
2,0,24208,제주 T무인텔,1,Motel,18:00,12:00,5.035050e+10,제주특별자치도 제주시 조천읍 남조로 2393,제주시,조천읍,한림읍 협재로 68-5,126.246960,33.392206,https://yaimg.yanolja.com/v5/2018/09/10/16/640...,NaN,NaN,NaN
3,0,24208,제주 T무인텔,1,Motel,18:00,12:00,5.035050e+10,제주특별자치도 제주시 조천읍 남조로 2393,제주시,조천읍,한림읍 협재로 68-5,126.246960,33.392206,https://yaimg.yanolja.com/v5/2018/09/10/16/640...,NaN,NaN,친절함
4,0,24208,제주 T무인텔,1,Motel,18:00,12:00,5.035050e+10,제주특별자치도 제주시 조천읍 남조로 2393,제주시,조천읍,한림읍 협재로 68-5,126.246960,33.392206,https://yaimg.yanolja.com/v5/2018/09/10/16/640...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27437,1533,1000122715,제주 델마펜션,3,Pension,16:00,11:00,5.035059e+10,제주특별자치도 제주시 연대마을길 16-8,제주시,연대마을,애월읍 고성서3길 19,126.411661,33.465629,https://yaimg.yanolja.com/v5/2022/11/09/15/640...,NaN,NaN,깨끗함
27438,1533,1000122715,제주 델마펜션,3,Pension,16:00,11:00,5.035059e+10,제주특별자치도 제주시 연대마을길 16-8,제주시,연대마을,애월읍 고성서3길 19,126.411661,33.465629,https://yaimg.yanolja.com/v5/2022/11/09/15/640...,NaN,NaN,NaN
27439,1533,1000122715,제주 델마펜션,3,Pension,16:00,11:00,5.035059e+10,제주특별자치도 제주시 연대마을길 16-8,제주시,연대마을,애월읍 고성서3길 19,126.411661,33.465629,https://yaimg.yanolja.com/v5/2022/11/09/15/640...,NaN,NaN,깨끗함
27440,1533,1000122715,제주 델마펜션,3,Pension,16:00,11:00,5.035059e+10,제주특별자치도 제주시 연대마을길 16-8,제주시,연대마을,애월읍 고성서3길 19,126.411661,33.465629,https://yaimg.yanolja.com/v5/2022/11/09/15/640...,NaN,NaN,외관
27441,1536,1000123163,제주 달콤한아침펜션,3,Pension,17:00,10:00,5.035059e+10,제주특별자치도 제주시 구좌읍 행원로 35-9,제주시,구좌읍,영평5길 68,126.578177,33.484781,https://yaimg.yanolja.com/v5/2023/01/02/10/640...,NaN,옥상에서 바다 감상 가능 / 빔프로젝터 / 조식 / 월정리 해수욕장 도보 5분 / ...,깨끗함